FROM nvidia/cuda:12.4.1-base-ubuntu22.04
MAINTAINER ZhangtaoLab "liuguanqing@zhangtaolab.org"

RUN apt update
RUN apt install -y git python3 python3-pip
RUN python3 -m pip install --no-cache-dir --upgrade pip

RUN python3 -m pip install --no-cache-dir transformers==4.41.2 tokenizers==0.19.1 modelscope==1.19.0

# If set to nothing, will install the latest version
ARG PYTORCH='2.3.0'

RUN [ ${#PYTORCH} -gt 0 ] && VERSION='torch=='$PYTORCH'.*' ||  VERSION='torch'; python3 -m pip install --no-cache-dir -U $VERSION --extra-index-url https://download.pytorch.org/whl/cpu

RUN python3 -m pip install --no-cache-dir tqdm regex 'numpy<2' pandas scikit_learn packaging sentencepiece tensorboardX

RUN python3 -m pip uninstall -y tensorflow flax

ENV RUN_USER=user \
    RUN_UID=1234 \
    RUN_GID=1234 \
    RUN_HOME=/home/user

RUN groupadd -r $RUN_USER -g $RUN_UID
RUN useradd -u $RUN_UID -r -g $RUN_GID -d $RUN_HOME -c "LLMs user" $RUN_USER

ADD ./inference.py $RUN_HOME/inference.py
RUN chmod +x $RUN_HOME/inference.py

ADD ./entrypoint.sh /usr/bin/model_inference
RUN chmod +x /usr/bin/model_inference

WORKDIR $RUN_HOME

ENTRYPOINT ["/usr/bin/model_inference"]
